### PR TITLE
added sv translation

### PR DESCRIPTION
**Pull request by klasrocket**
copied the en folder to make a sv(swedish) translation and replaced the strings in the strings.xml file

### CODE REVIEW

**Comment by Sav22999** [comment]
For the reason of #5 i will wait until the 0.0.14a update :) then I'll merge it. Thanks again

**Comment by klasrocket** [comment]
after compiling and testing I realized that the language in the app does not change and the listen section did not fetch sentences but after changing the locale from sv to sv-SE according to this; https://github.com/Common-Voice/sentence-collector/issues/207
i got the sentences-server connection to work (that's whats improtant for me) but the app language is still english, even if I change to italian and restart the app.

**Comment by Sav22999** [comment]
Basically, if your device language is Swedish, (and the ISO code of swedish is SV) it will import and show automatically it in that language (you have to put the language file on res>values-sv folder of app). Anyway, no problem, as soon as I have some minutes I will add your language 😃
(To semplify the process of translation, I put every time strings in "Languages" folder of github)

If you need more support, you can also contact me on Telegram 😃

**Comment by klasrocket** [comment]
Ahh, then it makes sence, got the system language set to EN

**Comment by Sav22999** [comment]
@klasrocket I've updated strings. Unfortunately there are some conflicts now 😅

**Comment by Sav22999** [comment]
Because you create a new PR #7 i close this one

**Pull request closed without merging**
