### PR TITLE
2 2alpha

### PR DESCRIPTION
**Pull request by bentleypark**

### CODE REVIEW

**Comment by Sav22999** [comment]
@bentleypark Thanks again! 😄

**Comment by Sav22999** [comment]
@bentleypark If you still want to contribute, you can see on Trello https://trello.com/b/gbXqmHOL/common-voice-android.

Update me 😄

**Comment by bentleypark** [comment]
@Sav22999 Thanks :) I'll check it out.

**Comment by Sav22999** [comment]
@bentleypark if you want to work to one of those feature (in Trello), please write to me (on Telegram: Sav22999) your email address, so I can add you to Trello :smile:

**Comment by Sav22999** [comment]
With the agreement also of @MrIndeciso I approve this PR

**Comment by bentleypark** [comment]
> @bentleypark if you want to work to one of those feature (in Trello), please write to me (on Telegram: Sav22999) your email address, so I can add you to Trello :smile: 

@Sav22999 Ok! I'll do it.

**Comment by MrIndeciso** [comment]
Hi @bentleypark, is it ok for you if we create a Telegram group to talk about the development?
I am rewriting or changing lots of files right now, so I am worried that merge conflicts might occur if we don't coordinate in what we edit.

**Comment by bentleypark** [comment]
@MrIndeciso Sure. Please add me to Telegram group once the group is ready. I also sent message to @Sav22999 on Telegram.

**Pull request merged**
